Hall Management System/Hall Management System/Models/ErrorViewModel.cs
using System;

namespace Hall_Management_System.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hall Management System/Hall Management System/Controllers/HallController.cs
using HallManagementSystem.Database.Model;
using HallManagementSystem.Repo;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Hall_Management_System.Controllers
{
    public class HallController : Controller
    {
        public IActionResult Index()
        {
            HallRepo st = new HallRepo();
            List<Hall> hallList=new List<Hall>();   
            try
            {
                 hallList = st.GetHall();
            }
            catch (Exception ex)
            {
                string error = ex.Message;
            }
             return View(hallList);
        }
        //GET
        public IActionResult Add()
        {      
            return View();
        }

        //POST
        [HttpPost]
        public IActionResult Add(Hall model)
        {
            if (ModelState.IsValid)
            {
            HallRepo hr = new HallRepo();
            hr.Add(model);
            return RedirectToAction("Index");
            }
            return View(model);
        }

        //GET
        public IActionResult Edit(int id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            HallRepo st = new HallRepo();
            var model = st.GetById(id);
            if(model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        //POST
        [HttpPost]
        public IActionResult Edit(Hall model)
        {
            if (ModelState.IsValid)
            {
                HallRepo hr = new HallRepo();
                hr.Update(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //GET
        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            HallRepo st = new HallRepo();
            var model = st.GetById(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        //POST
        [HttpPost]
        public IActionResult Delete(Hall model)
        {
                HallRepo hr = new HallRepo();
                hr.Delete(model);
                return RedirectToAction("Index");    
        }
    }
}

Hall Management System/Hall Management System/Controllers/HomeController.cs
using Hall_Management_System;
using Hall_Management_System.Models;
using HallManagementSystem.Database;
using HallManagementSystem.Repo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hall_Management_System.Controllers
{
    public class HomeController : Controller
    {

        public HomeController()
        {
          
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hall Management System/Hall Management System/Controllers/MeetingController.cs
using HallManagementSystem.Database;
using HallManagementSystem.Database.Model;
using HallManagementSystem.Repo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Hall_Management_System.Controllers
{
    public class MeetingController : Controller
    {
        private readonly ApplicationContext db;
        public MeetingController(ApplicationContext db)
        {
            this.db = db;
        }
    
        public IActionResult Index()
        {
            MeetingRepo mt = new MeetingRepo();
            List<Meeting> meetingList = new List<Meeting>();
            try
            {
                meetingList = mt.GetMeeting();
            }
            catch (Exception ex)
            {
                string error = ex.Message;
            }
            return View(meetingList);

            //var model = db.tbMeeting.Include(d => d.Hall);
            //return View(model);
        }

        //GET
        public IActionResult Add()
        {
            IEnumerable<SelectListItem> TypeDropDown = db.tbHall.Select(i => new SelectListItem
            {
                Text= i.Name,
                Value=i.Id.ToString()
            });
            ViewBag.TypeDropDown = TypeDropDown;    
            return View();
        }

        //POST
        [HttpPost]
        public IActionResult Add(Meeting model)
        {
            if (ModelState.IsValid)
            {
                MeetingRepo mr = new MeetingRepo();
                mr.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

Hall Management System/Hall Management System/Views/Hall/Add.cshtml
@using HallManagementSystem.Database.Model
@model Hall

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Hall</h2>
            <hr />
        </div>
        <div class ="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="Location"></label>
            <input asp-for="Location" class="form-control" />
            <span asp-validation-for="Location" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="Capacity"></label>
            <input asp-for="Capacity" class="form-control" />
            <span asp-validation-for="Capacity" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div> 
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Hall" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
    </div>
</form>

Hall Management System/Hall Management System/Views/Hall/Delete.cshtml
@using HallManagementSystem.Database.Model
@model Hall

<form method="post" asp-action="Delete">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Hall</h2>
            <hr />
        </div>
        <div class ="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div> 
        <div class ="mb-3">
            <label asp-for="Location"></label>
            <input asp-for="Location" disabled class="form-control" />
        </div> 
        <div class ="mb-3">
            <label asp-for="Capacity"></label>
            <input asp-for="Capacity" disabled class="form-control" />
        </div> 
        <div class ="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" disabled class="form-control" />
        </div> 
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Hall" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
    </div>
</form>

Hall Management System/Hall Management System/Views/Hall/Edit.cshtml
@using HallManagementSystem.Database.Model
@model Hall

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Hall</h2>
            <hr />
        </div>
        <div class ="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="Location"></label>
            <input asp-for="Location" class="form-control" />
            <span asp-validation-for="Location" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="Capacity"></label>
            <input asp-for="Capacity" class="form-control" />
            <span asp-validation-for="Capacity" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div> 
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Hall" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
    </div>
</form>

Hall Management System/Hall Management System/Views/Hall/Index.cshtml
@using HallManagementSystem.Database.Model
@model List<Hall>
@{
    ViewData["Title"] = "Index";
}

@*<h1>Hall Lists</h1>*@

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Hall Lists</h2>
        </div>
        <div class="col-6 text-end" >
           <a asp-controller="Hall" asp-action="Add"class="btn btn-primary"><i class="bi bi-plus-circle"></i>&nbsp;  Add New Hall
           </a>
        </div>
    </div>
    <br /><br />
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Hall Name
            </th>
            <th>
                Location
            </th>
            <th>
                Capacity
            </th>
            <th>
                Description
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="30%">
                    @obj.Name
                </td>
                <td width="10%">
                    @obj.Location
                </td>
                <td width="10%">
                    @obj.Capacity
                </td>
                <td width="30%">
                    @obj.Description
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Hall" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                    </div>
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Hall" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

Hall Management System/Hall Management System/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Hall Management System</h1>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>

Hall Management System/Hall Management System/Views/Meeting/Add.cshtml
@using HallManagementSystem.Database.Model
@model Meeting

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Hall</h2>
            <hr />
        </div>
        <div class ="mb-3">
            <label asp-for="MeetingTopic">Meeting Topic</label>
            <input asp-for="MeetingTopic" class="form-control" />
            <span asp-validation-for="MeetingTopic" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="StartTime">Start Time</label>
            <input asp-for="StartTime" class="form-control" />
            <span asp-validation-for="StartTime" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="EndTime">End Time</label>
            <input asp-for="EndTime" class="form-control" />
            <span asp-validation-for="EndTime" class="text-danger"></span>
        </div> 
        <div class ="mb-3">
            <label asp-for="HallId">Hall Name</label>
            <select asp-for="HallId" asp-items="@ViewBag.TypeDropDown" class="form-control">
            <option selected>--Select Hall--</option>
            </select>
            <span asp-validation-for="HallId" class="text-danger"></span>
        </div> 
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Meeting" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
    </div>
</form>

Hall Management System/Hall Management System/Views/Meeting/Index.cshtml
@using HallManagementSystem.Database.Model
@model List<Meeting>


@{
    ViewData["Title"] = "Index";
}

@*<h1>Meeting Lists</h1>*@

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Meeting Lists</h2>
        </div>
        <div class="col-6 text-end" >
           <a asp-controller="Meeting" asp-action="Add"class="btn btn-primary"><i class="bi bi-plus-circle"></i>&nbsp;  Add New Meeting
           </a>
        </div>
    </div>
    <br /><br />
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Meeting Topic
            </th>
            <th>
                Start Time
            </th>
            <th>
                End Time
            </th>
            <th>
                Hall Name
            </th>
            <th>
                Hall Location
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="30%">
                    @obj.MeetingTopic
                </td>
                <td width="10%">
                    @obj.StartTime
                </td>
                <td width="10%">
                    @obj.EndTime
                <td width="10%">
                    @*@obj.Hall.Name*@
                </td>
                <td width="10%"> 
                    @*@obj.Hall.Location*@
               </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Meeting" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                    </div>
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Meeting" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

Hall Management System/Hall Management System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hall_Management_System</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
     @*default [~/lib/bootstrap/dist/css/bootstrap.min.css]*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
           <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
         <a class="nav-link " asp-area="" asp-controller="Hall" asp-action="Index">Hall</a>
         <li class="nav-item">
         <a class="nav-link " asp-area="" asp-controller="Meeting" asp-action="Index">Meeting</a>
        @*</li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>*@
        @*<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
     @* <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>
       @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hall_Management_System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hall" asp-action="Index">Hall</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - Hall_Management_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>